# Generated by Django 3.0 on 2019-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crange', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ctype', models.CharField(choices=[('quan', 'качественный'), ('qual', 'количественный')], max_length=4)),
                ('optim', models.CharField(blank=True, choices=[('max', 'Максимум'), ('min', 'Минимум')], max_length=3, null=True)),
                ('measurement', models.CharField(max_length=20)),
                ('scale', models.CharField(choices=[('nominal', 'Наименований'), ('ordinal', 'Порядковая'), ('interval', 'Интервалов'), ('ratio', 'Отношений'), ('difference', 'Разностей'), ('absolute', 'Абсолютная')], max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='House',
            new_name='Alternative',
        ),
    ]
