# Generated by Django 3.0 on 2019-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191203_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterion',
            old_name='ctype',
            new_name='criterion_type',
        ),
        migrations.RenameField(
            model_name='criterion',
            old_name='optim',
            new_name='optimization_type',
        ),
        migrations.RenameField(
            model_name='criterion',
            old_name='crange',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mrange',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='prange',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='alternative',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
