# Generated by Django 3.0 on 2019-12-03 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191203_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='normalized',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
