# Generated by Django 3.0 on 2019-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='measurement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
