# Generated by Django 3.0 on 2019-12-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191204_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='alternatives',
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Alternative')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mark')),
            ],
        ),
    ]
