# Generated by Django 3.0 on 2019-12-23 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191218_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='number',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
