# Generated by Django 3.0 on 2019-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191223_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
